### ISSUE TITLE
Reverse proxy setup install file is missing

### ISSUE THREAD

**Issue by ekohl** [superfantasticawesome/boltello#42]
The actual template file is missing. It's mentioned here:
https://github.com/superfantasticawesome/boltello/blob/9af3a0b91b509e123278a27b784911b55b9bec75/modules/boltello_builder/manifests/reverse_proxy.pp#L23

**Comment by superfantasticawesome** [comment]
That file is created here: https://github.com/superfantasticawesome/boltello/blob/main/tasks/configure_directories.sh#L29
