### ISSUE TITLE
Use Apache for the reverse proxy?

### ISSUE THREAD

**Issue by ekohl** [superfantasticawesome/boltello#44]
Apache is already used all over the stack. Any particular reason you're pulling in nginx here?

**Comment by superfantasticawesome** [comment]
That would mean hacking pulp's configuration to add proxy pass directives for botlello's reverse proxy (for puppet).
If I knew of an easy way to modify that configuration I would do it; precisely for the reason stated in your question.

**Comment by ekohl** [comment]
Couldn't you define a new vhost? https://github.com/puppetlabs/puppetlabs-apache is the module in question and we use `apache::vhost` quite a bit. Define that on a new port and it's neatly isolated.

**Comment by superfantasticawesome** [comment]
thanks. I'm investigating now :)

**Comment by superfantasticawesome** [comment]
> Apache is already used all over the stack. Any particular reason you're pulling in nginx here?

Hello Ewoud. Any chance you've got a define file handy for proxying puppetserver with puppetlabs-apache?

**Comment by superfantasticawesome** [comment]
I couldn't get this working. I looked at the following links and exhausted every solution and combination of solutions provided.... 
https://puppet.com/docs/puppet/6.18/server/external_ssl_termination.html
https://tickets.puppetlabs.com/browse/SERVER-18
https://tickets.puppetlabs.com/browse/SERVER-213
https://tickets.puppetlabs.com/browse/SERVER-217

The reverse proxy works with Nginx; however, that was only after I changed to ssl_client_{i,s}_dn_legacy headers: https://serverfault.com/questions/829754/why-did-the-format-of-nginx-ssl-client-i-dn-suddenly-change

I've tried using the Apache analogue, 'LegacyDNStringFormat' in SSLOptions to no avail.
If anyone has some insight on this I'd appreciate a working config.

Some initial certificate verification to prove the solution works:
katello server:
katello-certs-check -c /etc/puppetlabs/puppet/ssl/certs/$(hostname).pem \
-k /etc/puppetlabs/puppet/ssl/private_keys/$(hostname).pem \
-b /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem
proxy server:
katello-certs-check -c /etc/puppetlabs/puppet/ssl/certs/$(hostname).pem \
-k /etc/puppetlabs/puppet/ssl/private_keys/$(hostname).pem \
-b /etc/puppetlabs/puppet/ssl/certs/ca.pem
openssl s_client -host <katello server fqdn> -port 8140 \
-cert /etc/puppetlabs/puppet/ssl/certs/$(hostname).pem \
-key /etc/puppetlabs/puppet/ssl/private_keys/$(hostname).pem \
-CAfile /var/lib/puppet/ssl/certs/ca.pem

Unfortunately, that's all I have on this.

**Comment by ekohl** [comment]
It does indeed look like this is a problem with the Apache version included in EL7. That makes the use of nginx a good choice for now. When the stack is upgraded to EL8 or newer it can be reconsidered. Closing it for now.

**Comment by superfantasticawesome** [comment]
Thanks!

Gerard Ryan
mobile: 718-450-1416
skype: gerard.ryan31
