### ISSUE TITLE
document components update

### ISSUE THREAD

**Issue by vchepkov** [superfantasticawesome/boltello#56]
Please document how to properly update infrastructure components, for example, from foreman 2.1.3 to 2.1.4
Since plans support only X.Y versions and we can't run `foreman-installer` as one normally would

**Comment by superfantasticawesome** [comment]
This behavior hassn't been modeled yet.
It's currently only possible to update major.minor increment; not patch-level.
Thoughts are welcome.

**Comment by superfantasticawesome** [comment]
Ok... the boltello::katello_upgrade plan will uclock all locked packages found in [boltello::versionlock_packages](data/plans/common.yaml#L66)

Once the packages are unlocked, the plan reads in version data from command arguments and compares those versions with:
- package versions on disk
- package version from Hiera

Provided you're not over-patching or, in the case of stale Hiera data, under-patching, the plan will attempt to install package versions specified in the command arguments.

Over-patching means you have versions in Hiera that are (0.02 < desired_version)
Under-patching means you have versions on disk that are the same or more than (0.009 > desired_version)
I think that explains it... I'll provide an example and hope it makes sense visually:

Say you want to install katello-3.17 and you have katello-3.14 installed... and the (installed_version == argument_version)
NOTE: You will need to independantly verify corresponding release versions between foreman and katello

The documentation indicates that upgrades can only occur incrementally... so from the command line:
targets='katello.internal,proxy1.internal,proxy2.internal'
bolt plan run boltello::katello_upgrade --targets $targets katello_version=3.15 foreman_version=2.0
bolt plan run boltello::katello_upgrade --targets $targets katello_version=3.16 foreman_version=2.1
bolt plan run boltello::katello_upgrade --targets $targets katello_version=3.17 foreman_version=2.2

This will pick up any "infrastructure" components, or patch level updates; e.g., katello-3.16.1**-1**.el7.noarch, or, katello-3.16.1-[*].el7.noarch

**Comment by superfantasticawesome** [comment]
PS: you can update Foreman only by incrementing it's version number on the command line and leaving Katello at the same version. Vice versa for Katello
